### ISSUE TITLE
Invalid syntax error on line 114

### ISSUE THREAD

**Issue by Musrar** [quantenProjects/dict.cc.offline.py#2]
```
 File "dict.py", line 114
    print colors(j), i[1].ljust(terminalwidthhalf),i[2].ljust(terminalwidthhalf-8),'\033[49m' #formating output
          ^
SyntaxError: invalid syntax
```
: (

**Comment by Musrar** [comment]
Ok, nvm, I had to change syntax of print because of python3.

**Comment by quantenProjects** [comment]
oh, its still python2 :see_no_evil: I haven't used it for years.

It would be great, if you would open a pull request with your python3 port :smiley:

**Comment by Musrar** [comment]
I'm going to do so now. Although it only worked with Ubuntu 20.04, when I tried it on Windows 10 the bash colours didn't display xD As if it couldn't interpret them as colours codes.

PS: I'm a noob, I don't know how to open a pull request xD

**Comment by quantenProjects** [comment]
You will have to fork my repo, commit your changes in your repo and then create a pull request. For additional info, may have a look here: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by Musrar** [comment]
Ok, after a week finally decided to get around github. I posted the pull request.

**Comment by quantenProjects** [comment]
Perfect :+1: Thank you. I have merged it.
